services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python your_script.py
    envVars:
      - key: TOKEN
        sync: false
    autoDeploy: true
